# 普通
# 占位符
name: fanyuexin
name1: fanyuexin${random.int}
name2: ${name}
name3: ${name:default}


# 对象
person:
  name: fanyuexin
  age: 3

#行内写法
#person：{name: fanyuexin,age: 3}

# 数组
pets:
  - cat
  - dog
  - pig

#行内写法
#pets: [cat,dog,pig]


#多环境配置，多文件，也可以单文件用---分隔
spring:
  profiles:
    active: dev
  mvc:
    format:
      date: dd/MM/yyyy


